server:
  port: 9090
spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  cassandra:
    keyspace-name: tacocloud
    schema-action: recreate
    local-datacenter: datacenter1
#    username: tacocloud
#    password: dkfj23sfs329