server:
  port: 9090
spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud;NON_KEYWORDS=user
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE